# Generated by Django 3.0.8 on 2020-08-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daily.State')),
            ],
            options={
                'db_table': 'economic_status',
            },
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covered_employment', models.FloatField()),
                ('insured_unemployment_rate', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('economic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='economy.EconomicStatus')),
            ],
            options={
                'db_table': 'employment_status',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_claims', models.IntegerField()),
                ('continued_claims', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('economic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='economy.EconomicStatus')),
            ],
            options={
                'db_table': 'claims',
            },
        ),
    ]
